spring:
  application:
    name: my-eureka-server
server:
  port: 8001

eureka:
  instance:
    hostname: MyEurekaServer
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
